# docker-compose.yml
version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./invoice-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./invoice-client
    ports:
      - "3001:3000"
    depends_on:
      - backend
