# Frontend Dockerfile
FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

EXPOSE 3000
CMD ["npm", "start"]
